import type { Rule } from '../../../../../types/rightPanelProps';
import type { InstanceScope } from '../../common/InstanceScope.types';
import { validateFieldPath } from '../../../../../utils/fieldPathValidator';

/**
 * ARRAY LENGTH RULE HELPERS
 * 
 * Build and parse ArrayLength rules for the unified RuleForm architecture.
 * 
 * PHASE 4: Stores instanceScope and fieldPath as structured properties
 * FIXED ERROR CODE: ARRAY_LENGTH_VIOLATION (cannot be changed by user)
 * 
 * Rule Structure:
 * - type: "ArrayLength"
 * - instanceScope: Structured instance scope object
 * - fieldPath: Resource-relative array path
 * - path: Legacy composed path (backward compat)
 * - params.min: Minimum length (optional)
 * - params.max: Maximum length (optional)
 * - errorCode: "ARRAY_LENGTH_VIOLATION" (fixed)
 */

interface BuildArrayLengthRuleParams {
  resourceType: string;
  instanceScope: InstanceScope;
  arrayPath: string;
  min?: number;
  max?: number;
  severity: 'error' | 'warning' | 'information';
  userHint?: string;
}

/**
 * Build an ArrayLength rule from form data.
 * PHASE 4: Stores instanceScope and fieldPath as separate properties
 */
export function buildArrayLengthRule(params: BuildArrayLengthRuleParams): Rule {
  const {
    resourceType,
    instanceScope,
    arrayPath,
    min,
    max,
    severity,
    userHint,
  } = params;

  // Validate field path (should be resource-relative)
  const validation = validateFieldPath(arrayPath);
  if (!validation.isValid) {
    throw new Error(`Invalid field path: ${validation.errorMessage}`);
  }

  const ruleParams: { min?: number; max?: number } = {};
  if (min !== undefined) ruleParams.min = min;
  if (max !== undefined) ruleParams.max = max;

  return {
    id: `rule-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
    type: 'ArrayLength',
    resourceType,
    instanceScope,
    fieldPath: arrayPath,
    severity,
    // errorCode removed - backend-owned
    params: ruleParams,
    userHint,
    message: '', // Will be generated by backend
    isMessageCustomized: false,
  };
}

/**
 * Parse an ArrayLength rule for editing.
 * Extracts array path and min/max constraints from rule definition.
 */
export function parseArrayLengthRule(rule: Rule): {
  arrayPath: string;
  min?: number;
  max?: number;
} {
  // arrayPath is already resource-relative
  const arrayPath = rule.fieldPath || '';
  
  const min = rule.params?.min !== undefined ? Number(rule.params.min) : undefined;
  const max = rule.params?.max !== undefined ? Number(rule.params.max) : undefined;

  return {
    arrayPath,
    min,
    max,
  };
}
