import type { Rule } from '../../../../../types/rightPanelProps';
import type { InstanceScope } from '../../common/InstanceScope.types';
import { composeInstanceScopedPath } from '../../common/InstanceScope.utils';

/**
 * ARRAY LENGTH RULE HELPERS
 * 
 * Build and parse ArrayLength rules for the unified RuleForm architecture.
 * 
 * FIXED ERROR CODE: ARRAY_LENGTH_VIOLATION (cannot be changed by user)
 * 
 * Rule Structure:
 * - type: "ArrayLength"
 * - path: Full FHIRPath (e.g., "Patient[*].name")
 * - params.min: Minimum length (optional)
 * - params.max: Maximum length (optional)
 * - errorCode: "ARRAY_LENGTH_VIOLATION" (fixed)
 */

interface BuildArrayLengthRuleParams {
  resourceType: string;
  instanceScope: InstanceScope;
  arrayPath: string;
  min?: number;
  max?: number;
  severity: 'error' | 'warning' | 'information';
  errorCode: string;
  userHint?: string;
}

/**
 * Compose full FHIRPath from components.
 * Handles both full paths like "Patient[*].name" and relative paths like "name".
 */
function composeFhirPath(
  resourceType: string,
  instanceScope: InstanceScope,
  arrayPath: string
): string {
  const scopePath = composeInstanceScopedPath(resourceType, instanceScope);
  
  // Extract relative path if arrayPath starts with resource type
  let relativePath = arrayPath;
  
  if (arrayPath.startsWith(resourceType + '[')) {
    // Handle "Patient[*].name" → extract "name"
    const afterBracket = arrayPath.indexOf('].', resourceType.length);
    if (afterBracket > -1) {
      relativePath = arrayPath.substring(afterBracket + 2);
    }
  } else if (arrayPath.startsWith(resourceType + '.')) {
    // Handle "Patient.name" → extract "name"
    const resourceDotPrefix = resourceType + '.';
    relativePath = arrayPath.substring(resourceDotPrefix.length);
  }
  
  return `${scopePath}.${relativePath}`;
}

/**
 * Build an ArrayLength rule from form data.
 */
export function buildArrayLengthRule(params: BuildArrayLengthRuleParams): Rule {
  const {
    resourceType,
    instanceScope,
    arrayPath,
    min,
    max,
    severity,
    errorCode,
    userHint,
  } = params;

  const absolutePath = composeFhirPath(resourceType, instanceScope, arrayPath);

  const ruleParams: { min?: number; max?: number } = {};
  if (min !== undefined) ruleParams.min = min;
  if (max !== undefined) ruleParams.max = max;

  return {
    id: `rule-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
    type: 'ArrayLength',
    resourceType,
    path: absolutePath,
    severity,
    errorCode,
    params: ruleParams,
    userHint,
    message: '', // Will be generated by backend
    isMessageCustomized: false,
  };
}

/**
 * Parse an ArrayLength rule for editing.
 * Extracts array path and min/max constraints from rule definition.
 */
export function parseArrayLengthRule(rule: Rule): {
  arrayPath: string;
  min?: number;
  max?: number;
} {
  // Extract array path from full path
  const pathParts = rule.path?.split('.') || [];
  const arrayPath = pathParts.slice(1).join('.');
  
  const min = rule.params?.min !== undefined ? Number(rule.params.min) : undefined;
  const max = rule.params?.max !== undefined ? Number(rule.params.max) : undefined;

  return {
    arrayPath,
    min,
    max,
  };
}
