using Pss.FhirProcessor.Persistence.Models;
using Pss.FhirProcessor.Playground.Api.Models;
using System.Text.Json;

namespace Pss.FhirProcessor.Playground.Api.Mappers;

/// <summary>
/// Maps between API Project model and database ProjectRecord model.
/// Handles serialization/deserialization of features and nested JSON structures.
/// </summary>
public static class ProjectMapper
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        WriteIndented = false
    };

    /// <summary>
    /// Converts API Project model to database ProjectRecord model.
    /// </summary>
    public static ProjectRecord ToRecord(Project project)
    {
        return new ProjectRecord
        {
            Id = project.Id,
            Slug = string.Empty, // Will be auto-generated by repository
            Name = project.Name,
            Description = project.Description,
            RulesetJson = project.RulesJson ?? "{}",
            Status = "draft", // Default status for new projects
            FhirVersion = project.FhirVersion,
            CodeMasterJson = project.CodeMasterJson,
            SampleBundleJson = project.SampleBundleJson,
            ValidationSettingsJson = project.ValidationSettingsJson,
            FeaturesJson = SerializeFeatures(project.Features),
            CreatedAt = project.CreatedAt,
            UpdatedAt = project.UpdatedAt
        };
    }

    /// <summary>
    /// Converts database ProjectRecord model to API Project model.
    /// </summary>
    public static Project ToProject(ProjectRecord record)
    {
        return new Project
        {
            Id = record.Id,
            Name = record.Name,
            Description = record.Description,
            FhirVersion = record.FhirVersion,
            RulesJson = record.RulesetJson,
            CodeMasterJson = record.CodeMasterJson,
            SampleBundleJson = record.SampleBundleJson,
            ValidationSettingsJson = record.ValidationSettingsJson,
            FeaturesJson = record.FeaturesJson,
            CreatedAt = record.CreatedAt.DateTime,
            UpdatedAt = record.UpdatedAt.DateTime,
            Features = DeserializeFeatures(record.FeaturesJson)
        };
    }

    /// <summary>
    /// Converts API Project model to database ProjectRecord model for updates.
    /// Preserves existing slug and status.
    /// </summary>
    public static ProjectRecord ToRecordForUpdate(Project project, string slug, string status)
    {
        return new ProjectRecord
        {
            Id = project.Id,
            Slug = slug,
            Name = project.Name,
            Description = project.Description,
            RulesetJson = project.RulesJson ?? "{}",
            Status = status,
            FhirVersion = project.FhirVersion,
            CodeMasterJson = project.CodeMasterJson,
            SampleBundleJson = project.SampleBundleJson,
            ValidationSettingsJson = project.ValidationSettingsJson,
            FeaturesJson = SerializeFeatures(project.Features),
            CreatedAt = project.CreatedAt,
            UpdatedAt = DateTime.UtcNow
        };
    }

    /// <summary>
    /// Serializes ProjectFeatures to JSON string.
    /// </summary>
    private static string SerializeFeatures(ProjectFeatures features)
    {
        try
        {
            return JsonSerializer.Serialize(features, JsonOptions);
        }
        catch
        {
            return "{}";
        }
    }

    /// <summary>
    /// Deserializes ProjectFeatures from JSON string.
    /// Returns default instance if deserialization fails.
    /// </summary>
    private static ProjectFeatures DeserializeFeatures(string? json)
    {
        if (string.IsNullOrWhiteSpace(json))
        {
            return new ProjectFeatures();
        }

        try
        {
            return JsonSerializer.Deserialize<ProjectFeatures>(json) ?? new ProjectFeatures();
        }
        catch
        {
            return new ProjectFeatures();
        }
    }

    /// <summary>
    /// Converts list of ProjectRecords to ProjectMetadata list.
    /// </summary>
    public static IEnumerable<ProjectMetadata> ToMetadataList(IEnumerable<ProjectRecord> records)
    {
        return records.Select(record => new ProjectMetadata
        {
            Id = record.Id,
            Name = record.Name,
            Description = record.Description,
            FhirVersion = record.FhirVersion,
            CreatedAt = record.CreatedAt.DateTime,
            UpdatedAt = record.UpdatedAt.DateTime,
            HasRules = !string.IsNullOrWhiteSpace(record.RulesetJson) && record.RulesetJson != "{}",
            HasCodeMaster = !string.IsNullOrWhiteSpace(record.CodeMasterJson),
            HasSampleBundle = !string.IsNullOrWhiteSpace(record.SampleBundleJson)
        });
    }
}
