// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pss.FhirProcessor.Persistence.Data;

#nullable disable

namespace Pss.FhirProcessor.Persistence.Migrations
{
    [DbContext(typeof(FhirProcessorDbContext))]
    partial class FhirProcessorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pss.FhirProcessor.Persistence.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsPublicEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<string>("PolicyMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("policy_mode");

                    b.Property<string>("PublicId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("public_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_projects_public_id")
                        .HasFilter("public_id IS NOT NULL");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("Pss.FhirProcessor.Persistence.Models.ProjectArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArtifactType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("artifact_type");

                    b.Property<string>("CanonicalUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("canonical_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_path");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("ResourceJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("resource_json");

                    b.Property<string>("ResourceType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("resource_type");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_project_artifacts_project_id");

                    b.HasIndex("ProjectId", "CanonicalUrl")
                        .IsUnique()
                        .HasDatabaseName("ix_project_artifacts_project_id_canonical_url")
                        .HasFilter("canonical_url IS NOT NULL");

                    b.ToTable("project_artifacts", (string)null);
                });

            modelBuilder.Entity("Pss.FhirProcessor.Persistence.Models.ProjectBundle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BundleJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("bundle_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_project_bundles_project_id");

                    b.ToTable("project_bundles", (string)null);
                });

            modelBuilder.Entity("Pss.FhirProcessor.Persistence.Models.ProjectPublicLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("public_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_project_public_links_public_id");

                    b.ToTable("project_public_links", (string)null);
                });

            modelBuilder.Entity("Pss.FhirProcessor.Persistence.Models.ProjectRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BundleId")
                        .HasColumnType("uuid")
                        .HasColumnName("bundle_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("definition_json");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Provenance")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provenance");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rule_type");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scope");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BundleId")
                        .HasDatabaseName("ix_project_rules_bundle_id")
                        .HasFilter("bundle_id IS NOT NULL");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_project_rules_project_id");

                    b.ToTable("project_rules", (string)null);
                });

            modelBuilder.Entity("Pss.FhirProcessor.Persistence.Models.ProjectArtifact", b =>
                {
                    b.HasOne("Pss.FhirProcessor.Persistence.Models.Project", "Project")
                        .WithMany("Artifacts")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Pss.FhirProcessor.Persistence.Models.ProjectBundle", b =>
                {
                    b.HasOne("Pss.FhirProcessor.Persistence.Models.Project", "Project")
                        .WithMany("Bundles")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Pss.FhirProcessor.Persistence.Models.ProjectPublicLink", b =>
                {
                    b.HasOne("Pss.FhirProcessor.Persistence.Models.Project", "Project")
                        .WithMany("PublicLinks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Pss.FhirProcessor.Persistence.Models.ProjectRule", b =>
                {
                    b.HasOne("Pss.FhirProcessor.Persistence.Models.Project", "Project")
                        .WithMany("Rules")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Pss.FhirProcessor.Persistence.Models.Project", b =>
                {
                    b.Navigation("Artifacts");

                    b.Navigation("Bundles");

                    b.Navigation("PublicLinks");

                    b.Navigation("Rules");
                });
#pragma warning restore 612, 618
        }
    }
}
