import type { Rule } from '../../../../../types/rightPanelProps';
import type { InstanceScope } from '../../common/InstanceScope.types';
import { composeInstanceScopedPath } from '../../common/InstanceScope.utils';

/**
 * ALLOWED VALUES RULE HELPERS
 * 
 * Build and parse AllowedValues rules for the unified RuleForm architecture.
 * 
 * FIXED ERROR CODE: VALUE_NOT_ALLOWED (cannot be changed by user)
 * 
 * Rule Structure:
 * - type: "AllowedValues"
 * - path: Full FHIRPath (e.g., "Patient[*].gender")
 * - params.values: Array of allowed values
 * - errorCode: "VALUE_NOT_ALLOWED" (fixed)
 */

interface BuildAllowedValuesRuleParams {
  resourceType: string;
  instanceScope: InstanceScope;
  fieldPath: string;
  allowedValues: string[];
  severity: 'error' | 'warning' | 'information';
  errorCode: string;
  userHint?: string;
}

/**
 * Compose full FHIRPath from components.
 * Handles both full paths like "Patient[*].gender" and relative paths like "gender".
 */
function composeFhirPath(
  resourceType: string,
  instanceScope: InstanceScope,
  fieldPath: string
): string {
  const scopePath = composeInstanceScopedPath(resourceType, instanceScope);
  
  // Extract relative path if fieldPath starts with resource type
  let relativePath = fieldPath;
  
  if (fieldPath.startsWith(resourceType + '[')) {
    // Handle "Patient[*].gender" → extract "gender"
    const afterBracket = fieldPath.indexOf('].', resourceType.length);
    if (afterBracket > -1) {
      relativePath = fieldPath.substring(afterBracket + 2);
    }
  } else if (fieldPath.startsWith(resourceType + '.')) {
    // Handle "Patient.gender" → extract "gender"
    const resourceDotPrefix = resourceType + '.';
    relativePath = fieldPath.substring(resourceDotPrefix.length);
  }
  
  return `${scopePath}.${relativePath}`;
}

/**
 * Build an AllowedValues rule from form data.
 */
export function buildAllowedValuesRule(params: BuildAllowedValuesRuleParams): Rule {
  const {
    resourceType,
    instanceScope,
    fieldPath,
    allowedValues,
    severity,
    errorCode,
    userHint,
  } = params;

  const absolutePath = composeFhirPath(resourceType, instanceScope, fieldPath);

  return {
    id: `rule-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
    type: 'AllowedValues',
    resourceType,
    path: absolutePath,
    severity,
    errorCode,
    params: {
      values: allowedValues,
    },
    userHint,
    message: '', // Will be generated by backend
    isMessageCustomized: false,
  };
}

/**
 * Parse an AllowedValues rule for editing.
 * Extracts field path and allowed values from rule definition.
 */
export function parseAllowedValuesRule(rule: Rule): {
  fieldPath: string;
  allowedValues: string[];
} {
  // Extract field path from full path
  const pathParts = rule.path?.split('.') || [];
  const fieldPath = pathParts.slice(1).join('.');
  
  const allowedValues = Array.isArray(rule.params?.values) 
    ? rule.params.values.map((v: any) => v.toString())
    : [];

  return {
    fieldPath,
    allowedValues,
  };
}
