import type { Rule } from '../../../../../types/rightPanelProps';
import type { InstanceScope } from '../../common/InstanceScope.types';
import { validateFieldPath } from '../../../../../utils/fieldPathValidator';

/**
 * ALLOWED VALUES RULE HELPERS
 * 
 * Build and parse AllowedValues rules for the unified RuleForm architecture.
 * 
 * PHASE 4: Stores instanceScope and fieldPath as structured properties
 * FIXED ERROR CODE: VALUE_NOT_ALLOWED (cannot be changed by user)
 * 
 * Rule Structure:
 * - type: "AllowedValues"
 * - instanceScope: Structured instance scope object
 * - fieldPath: Resource-relative field path
 * - path: Legacy composed path (backward compat)
 * - params.values: Array of allowed values
 * - errorCode: "VALUE_NOT_ALLOWED" (fixed)
 */

interface BuildAllowedValuesRuleParams {
  resourceType: string;
  instanceScope: InstanceScope;
  fieldPath: string;
  allowedValues: string[];
  severity: 'error' | 'warning' | 'information';
  userHint?: string;
}

/**
 * Build an AllowedValues rule from form data.
 * PHASE 4: Stores instanceScope and fieldPath as separate properties
 */
export function buildAllowedValuesRule(params: BuildAllowedValuesRuleParams): Rule {
  const {
    resourceType,
    instanceScope,
    fieldPath,
    allowedValues,
    severity,
    userHint,
  } = params;

  // Validate field path (should be resource-relative)
  const validation = validateFieldPath(fieldPath);
  if (!validation.isValid) {
    throw new Error(`Invalid field path: ${validation.errorMessage}`);
  }

  return {
    id: `rule-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
    type: 'AllowedValues',
    resourceType,
    instanceScope,
    fieldPath,
    severity,
    // errorCode removed - backend-owned
    params: {
      values: allowedValues,
    },
    userHint,
    message: '', // Will be generated by backend
    isMessageCustomized: false,
  };
}

/**
 * Parse an AllowedValues rule for editing.
 * Extracts field path and allowed values from rule definition.
 */
export function parseAllowedValuesRule(rule: Rule): {
  fieldPath: string;
  allowedValues: string[];
} {
  // fieldPath is already resource-relative
  const fieldPath = rule.fieldPath || '';
  
  const allowedValues = Array.isArray(rule.params?.values) 
    ? rule.params.values.map((v: any) => v.toString())
    : [];

  return {
    fieldPath,
    allowedValues,
  };
}
