/**
 * Rule Suggestion Engine - Frontend Types
 * 
 * Type definitions for the deterministic (non-AI) rule suggestion system.
 * Suggestions are pattern-based detections with confidence scoring.
 */

export type RuleType = 
  | 'Regex'
  | 'AllowedValues'
  | 'FixedValue'
  | 'CodeSystem'
  | 'QuestionAnswer'
  | 'Resource'
  | 'Required'
  | 'ArrayLength'
  | 'CustomFhirPath';

export type ConfidenceLevel = 'Low' | 'Medium' | 'High';

/**
 * A rule suggestion generated by analyzing the bundle
 */
export interface RuleSuggestion {
  /** Type of rule being suggested */
  ruleType: RuleType;
  
  /** Target FHIRPath where the rule should be applied (without resource type prefix) */
  targetPath: string;
  
  /** Resource type this rule applies to */
  resourceType: string;
  
  /** Full rule configuration (apply-ready parameters) */
  parameters: Record<string, any>;
  
  /** Numeric confidence score (0-100) */
  confidenceScore: number;
  
  /** Categorical confidence level derived from score */
  confidenceLevel: ConfidenceLevel;
  
  /** Plain-English explanation of why this rule is suggested */
  rationale: string;
  
  /** Optional sample values observed in the bundle that led to this suggestion */
  sampleEvidence?: any[];
  
  /** Number of values observed that support this suggestion */
  sampleSize: number;
  
  /** Percentage of values that match the suggested pattern/constraint */
  coverage: number;
}

/**
 * Response from suggest-rules API endpoint
 */
export interface SuggestRulesResponse {
  projectId: string;
  suggestionCount: number;
  suggestions: RuleSuggestion[];
  minConfidenceScore: number;
  generatedAt: string;
}

/**
 * Request parameters for suggest-rules API
 */
export interface SuggestRulesRequest {
  minConfidence?: number;
}
