import type { Rule } from '../../../../../types/rightPanelProps';
import type { InstanceScope } from '../../common/InstanceScope.types';

/**
 * CUSTOM FHIRPATH RULE HELPERS
 * 
 * Build and parse CustomFHIRPath rules for the unified RuleForm architecture.
 * 
 * BACKEND-OWNED ERROR CODE: Backend determines CUSTOMFHIRPATH_CONDITION_FAILED at runtime.
 * 
 * Rule Structure:
 * - type: "CustomFHIRPath"
 * - path: Full FHIRPath with instance scope (e.g., "Patient[*]")
 * - params.expression: FHIRPath boolean expression
 * - errorCode: Backend-owned (frontend does not send)
 */

interface BuildCustomFHIRPathRuleParams {
  resourceType: string;
  instanceScope: InstanceScope;
  expression: string;
  severity: 'error' | 'warning' | 'information';
  userHint?: string;
}

/**
 * Build a CustomFHIRPath rule from form data.
 */
export function buildCustomFHIRPathRule(params: BuildCustomFHIRPathRuleParams): Rule {
  const {
    resourceType,
    instanceScope,
    expression,
    severity,
    userHint,
  } = params;

  return {
    id: `rule-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
    type: 'CustomFHIRPath',
    resourceType,
    fieldPath: '',
    instanceScope,
    severity,
    // errorCode removed - backend-owned
    params: {
      expression,
    },
    userHint,
    message: '', // Will be generated by backend
    isMessageCustomized: false,
  };
}

/**
 * Parse a CustomFHIRPath rule for editing.
 * Extracts expression from rule definition.
 */
export function parseCustomFHIRPathRule(rule: Rule): {
  expression: string;
} {
  const expression = rule.params?.expression?.toString() || '';

  return {
    expression,
  };
}
