import type { Rule } from '../../../../../types/rightPanelProps';
import type { InstanceScope } from '../../common/InstanceScope.types';
import { composeInstanceScopedPath } from '../../common/InstanceScope.utils';

/**
 * CUSTOM FHIRPATH RULE HELPERS
 * 
 * Build and parse CustomFHIRPath rules for the unified RuleForm architecture.
 * 
 * GOVERNED ERROR CODE: User must select from validated dropdown list.
 * 
 * Rule Structure:
 * - type: "CustomFHIRPath"
 * - path: Full FHIRPath with instance scope (e.g., "Patient[*]")
 * - params.expression: FHIRPath boolean expression
 * - errorCode: Selected from governed list (REQUIRED)
 */

interface BuildCustomFHIRPathRuleParams {
  resourceType: string;
  instanceScope: InstanceScope;
  expression: string;
  errorCode: string;
  severity: 'error' | 'warning' | 'information';
  userHint?: string;
}

/**
 * Build a CustomFHIRPath rule from form data.
 */
export function buildCustomFHIRPathRule(params: BuildCustomFHIRPathRuleParams): Rule {
  const {
    resourceType,
    instanceScope,
    expression,
    errorCode,
    severity,
    userHint,
  } = params;

  // For CustomFHIRPath, the path is just the resource with scope
  // The expression is stored in params and evaluated by the backend
  const path = composeInstanceScopedPath(resourceType, instanceScope);

  return {
    id: `rule-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
    type: 'CustomFHIRPath',
    resourceType,
    path,
    severity,
    errorCode,
    params: {
      expression,
    },
    userHint,
    message: '', // Will be generated by backend
    isMessageCustomized: false,
  };
}

/**
 * Parse a CustomFHIRPath rule for editing.
 * Extracts expression and errorCode from rule definition.
 */
export function parseCustomFHIRPathRule(rule: Rule): {
  expression: string;
  errorCode: string;
} {
  const expression = rule.params?.expression?.toString() || '';
  const errorCode = rule.errorCode || '';

  return {
    expression,
    errorCode,
  };
}
