import React, { useState } from 'react';
import { X, Sparkles, CheckCircle, AlertCircle, Info, ChevronDown, ChevronRight } from 'lucide-react';
import type { RuleSuggestion } from '../../types/ruleSuggestion';

interface RuleSuggestionsDrawerProps {
  isOpen: boolean;
  onClose: () => void;
  suggestions: RuleSuggestion[];
  onApplySuggestion: (suggestion: RuleSuggestion) => Promise<void>;
  onApplyAll: (suggestions: RuleSuggestion[]) => Promise<void>;
  isApplying?: boolean;
}

export const RuleSuggestionsDrawer: React.FC<RuleSuggestionsDrawerProps> = ({
  isOpen,
  onClose,
  suggestions,
  onApplySuggestion,
  onApplyAll,
  isApplying = false,
}) => {
  const [expandedIds, setExpandedIds] = useState<Set<number>>(new Set());
  const [selectedIds, setSelectedIds] = useState<Set<number>>(new Set());

  if (!isOpen) return null;

  const toggleExpanded = (index: number) => {
    const newExpanded = new Set(expandedIds);
    if (newExpanded.has(index)) {
      newExpanded.delete(index);
    } else {
      newExpanded.add(index);
    }
    setExpandedIds(newExpanded);
  };

  const toggleSelected = (index: number) => {
    const newSelected = new Set(selectedIds);
    if (newSelected.has(index)) {
      newSelected.delete(index);
    } else {
      newSelected.add(index);
    }
    setSelectedIds(newSelected);
  };

  const selectAll = () => {
    setSelectedIds(new Set(suggestions.map((_, i) => i)));
  };

  const deselectAll = () => {
    setSelectedIds(new Set());
  };

  const handleApplySelected = async () => {
    const selectedSuggestions = suggestions.filter((_, i) => selectedIds.has(i));
    await onApplyAll(selectedSuggestions);
    setSelectedIds(new Set());
  };

  const getConfidenceColor = (level: string) => {
    switch (level) {
      case 'High':
        return 'text-green-700 bg-green-50 border-green-200';
      case 'Medium':
        return 'text-amber-700 bg-amber-50 border-amber-200';
      case 'Low':
        return 'text-gray-700 bg-gray-50 border-gray-200';
      default:
        return 'text-gray-700 bg-gray-50 border-gray-200';
    }
  };

  const getConfidenceIcon = (level: string) => {
    switch (level) {
      case 'High':
        return <CheckCircle className="w-4 h-4" />;
      case 'Medium':
        return <AlertCircle className="w-4 h-4" />;
      case 'Low':
        return <Info className="w-4 h-4" />;
      default:
        return <Info className="w-4 h-4" />;
    }
  };

  return (
    <>
      {/* Backdrop */}
      <div
        className="fixed inset-0 bg-black bg-opacity-30 z-40"
        onClick={onClose}
      />

      {/* Drawer */}
      <div className="fixed right-0 top-0 h-full w-[600px] bg-white shadow-2xl z-50 flex flex-col">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-gray-200 bg-gradient-to-r from-purple-50 to-blue-50">
          <div className="flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-purple-600" />
            <h2 className="text-lg font-semibold text-gray-900">
              Rule Suggestions
            </h2>
            <span className="text-xs px-2 py-0.5 bg-white border border-gray-200 rounded text-gray-600">
              {suggestions.length} found
            </span>
          </div>
          <button
            onClick={onClose}
            className="p-1 hover:bg-white rounded transition-colors"
            disabled={isApplying}
          >
            <X className="w-5 h-5 text-gray-500" />
          </button>
        </div>

        {/* Info Banner */}
        <div className="px-6 py-3 bg-blue-50 border-b border-blue-100">
          <p className="text-xs text-blue-800">
            <strong>Pattern-Based Detection:</strong> These suggestions are generated by analyzing your bundle data deterministically—not using AI. Each suggestion includes a confidence score and rationale.
          </p>
        </div>

        {/* Bulk Actions */}
        {suggestions.length > 0 && (
          <div className="px-6 py-3 border-b border-gray-200 flex items-center justify-between bg-gray-50">
            <div className="flex items-center gap-2">
              <button
                onClick={selectAll}
                className="text-xs text-blue-600 hover:text-blue-700 font-medium"
                disabled={isApplying}
              >
                Select All
              </button>
              <span className="text-gray-300">|</span>
              <button
                onClick={deselectAll}
                className="text-xs text-gray-600 hover:text-gray-700 font-medium"
                disabled={isApplying}
              >
                Deselect All
              </button>
              {selectedIds.size > 0 && (
                <span className="text-xs text-gray-500 ml-2">
                  ({selectedIds.size} selected)
                </span>
              )}
            </div>
            {selectedIds.size > 0 && (
              <button
                onClick={handleApplySelected}
                disabled={isApplying}
                className="px-3 py-1.5 bg-blue-600 text-white text-sm rounded hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
              >
                {isApplying ? 'Applying...' : `Apply ${selectedIds.size} Selected`}
              </button>
            )}
          </div>
        )}

        {/* Suggestions List */}
        <div className="flex-1 overflow-y-auto px-6 py-4">
          {suggestions.length === 0 ? (
            <div className="text-center py-12 text-gray-500">
              <Sparkles className="w-12 h-12 mx-auto mb-3 text-gray-300" />
              <p className="text-sm">No rule suggestions found</p>
              <p className="text-xs mt-1">Your bundle data doesn't contain detectable patterns</p>
            </div>
          ) : (
            <div className="space-y-3">
              {suggestions.map((suggestion, index) => {
                const isExpanded = expandedIds.has(index);
                const isSelected = selectedIds.has(index);

                return (
                  <div
                    key={index}
                    className={`border rounded-lg transition-all ${
                      isSelected ? 'border-blue-300 bg-blue-50' : 'border-gray-200 bg-white'
                    }`}
                  >
                    {/* Suggestion Header */}
                    <div className="p-4">
                      <div className="flex items-start gap-3">
                        {/* Checkbox */}
                        <input
                          type="checkbox"
                          checked={isSelected}
                          onChange={() => toggleSelected(index)}
                          className="mt-1 w-4 h-4 text-blue-600 border-gray-300 rounded focus:ring-blue-500"
                          disabled={isApplying}
                        />

                        {/* Content */}
                        <div className="flex-1 min-w-0">
                          {/* Rule Type & Path */}
                          <div className="flex items-center gap-2 mb-2">
                            <span className="font-mono text-sm font-semibold text-gray-900">
                              {suggestion.resourceType}.{suggestion.targetPath}
                            </span>
                            <span className="px-2 py-0.5 bg-purple-100 text-purple-700 text-xs rounded font-medium">
                              {suggestion.ruleType}
                            </span>
                          </div>

                          {/* Confidence Badge */}
                          <div className={`inline-flex items-center gap-1.5 px-2 py-1 rounded border text-xs font-medium ${getConfidenceColor(suggestion.confidenceLevel)}`}>
                            {getConfidenceIcon(suggestion.confidenceLevel)}
                            <span>{suggestion.confidenceLevel} Confidence</span>
                            <span className="ml-1 text-xs opacity-75">
                              ({Math.round(suggestion.confidenceScore)}/100)
                            </span>
                          </div>

                          {/* Rationale */}
                          <p className="text-sm text-gray-700 mt-2">
                            {suggestion.rationale}
                          </p>

                          {/* Sample Evidence Preview */}
                          {suggestion.sampleEvidence && suggestion.sampleEvidence.length > 0 && (
                            <div className="mt-2 text-xs text-gray-600">
                              <span className="font-medium">Sample: </span>
                              <span className="font-mono">
                                {JSON.stringify(suggestion.sampleEvidence[0])}
                                {suggestion.sampleEvidence.length > 1 && ` +${suggestion.sampleEvidence.length - 1} more`}
                              </span>
                            </div>
                          )}

                          {/* Toggle Details Button */}
                          <button
                            onClick={() => toggleExpanded(index)}
                            className="mt-3 flex items-center gap-1 text-xs text-blue-600 hover:text-blue-700 font-medium"
                          >
                            {isExpanded ? (
                              <>
                                <ChevronDown className="w-3 h-3" />
                                Hide Details
                              </>
                            ) : (
                              <>
                                <ChevronRight className="w-3 h-3" />
                                Show Details
                              </>
                            )}
                          </button>
                        </div>

                        {/* Apply Button */}
                        <button
                          onClick={() => onApplySuggestion(suggestion)}
                          disabled={isApplying}
                          className="px-3 py-1.5 bg-white border border-gray-300 text-gray-700 text-sm rounded hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
                        >
                          Apply
                        </button>
                      </div>

                      {/* Expanded Details */}
                      {isExpanded && (
                        <div className="mt-4 pt-4 border-t border-gray-200 space-y-3">
                          {/* Parameters */}
                          <div>
                            <h4 className="text-xs font-semibold text-gray-700 uppercase tracking-wide mb-2">
                              Rule Parameters
                            </h4>
                            <pre className="text-xs bg-gray-50 border border-gray-200 rounded p-3 overflow-x-auto">
                              {JSON.stringify(suggestion.parameters, null, 2)}
                            </pre>
                          </div>

                          {/* Coverage Stats */}
                          <div>
                            <h4 className="text-xs font-semibold text-gray-700 uppercase tracking-wide mb-2">
                              Coverage Statistics
                            </h4>
                            <div className="grid grid-cols-2 gap-2 text-xs">
                              <div className="bg-gray-50 border border-gray-200 rounded p-2">
                                <span className="text-gray-600">Sample Size:</span>
                                <span className="ml-2 font-medium text-gray-900">
                                  {suggestion.sampleSize}
                                </span>
                              </div>
                              <div className="bg-gray-50 border border-gray-200 rounded p-2">
                                <span className="text-gray-600">Coverage:</span>
                                <span className="ml-2 font-medium text-gray-900">
                                  {Math.round(suggestion.coverage * 100)}%
                                </span>
                              </div>
                            </div>
                          </div>

                          {/* All Sample Evidence */}
                          {suggestion.sampleEvidence && suggestion.sampleEvidence.length > 0 && (
                            <div>
                              <h4 className="text-xs font-semibold text-gray-700 uppercase tracking-wide mb-2">
                                Sample Evidence
                              </h4>
                              <div className="space-y-1">
                                {suggestion.sampleEvidence.slice(0, 5).map((evidence, i) => (
                                  <div
                                    key={i}
                                    className="text-xs font-mono bg-gray-50 border border-gray-200 rounded px-2 py-1"
                                  >
                                    {JSON.stringify(evidence)}
                                  </div>
                                ))}
                                {suggestion.sampleEvidence.length > 5 && (
                                  <p className="text-xs text-gray-500 italic">
                                    ...and {suggestion.sampleEvidence.length - 5} more samples
                                  </p>
                                )}
                              </div>
                            </div>
                          )}
                        </div>
                      )}
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>
      </div>
    </>
  );
};
