import type { Rule } from '../../../../../types/rightPanelProps';
import type { InstanceScope } from '../../common/InstanceScope.types';
import { composeInstanceScopedPath } from '../../common/InstanceScope.utils';

/**
 * FIXED VALUE RULE HELPERS
 * 
 * Build and parse FixedValue rules for the unified RuleForm architecture.
 * 
 * FIXED ERROR CODE: FIXED_VALUE_MISMATCH (cannot be changed by user)
 * 
 * Rule Structure:
 * - type: "FixedValue"
 * - path: Full FHIRPath (e.g., "Patient[*].active")
 * - params.value: Expected value
 * - errorCode: "FIXED_VALUE_MISMATCH" (fixed)
 */

interface BuildFixedValueRuleParams {
  resourceType: string;
  instanceScope: InstanceScope;
  fieldPath: string;
  expectedValue: string;
  severity: 'error' | 'warning' | 'information';
  errorCode: string;
  userHint?: string;
}

/**
 * Compose full FHIRPath from components.
 * Handles both full paths like "Patient[*].active" and relative paths like "active".
 */
function composeFhirPath(
  resourceType: string,
  instanceScope: InstanceScope,
  fieldPath: string
): string {
  const scopePath = composeInstanceScopedPath(resourceType, instanceScope);
  
  // Extract relative path if fieldPath starts with resource type
  let relativePath = fieldPath;
  
  if (fieldPath.startsWith(resourceType + '[')) {
    // Handle "Patient[*].active" → extract "active"
    const afterBracket = fieldPath.indexOf('].', resourceType.length);
    if (afterBracket > -1) {
      relativePath = fieldPath.substring(afterBracket + 2);
    }
  } else if (fieldPath.startsWith(resourceType + '.')) {
    // Handle "Patient.active" → extract "active"
    const resourceDotPrefix = resourceType + '.';
    relativePath = fieldPath.substring(resourceDotPrefix.length);
  }
  
  return `${scopePath}.${relativePath}`;
}

/**
 * Build a FixedValue rule from form data.
 */
export function buildFixedValueRule(params: BuildFixedValueRuleParams): Rule {
  const {
    resourceType,
    instanceScope,
    fieldPath,
    expectedValue,
    severity,
    errorCode,
    userHint,
  } = params;

  const absolutePath = composeFhirPath(resourceType, instanceScope, fieldPath);

  return {
    id: `rule-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
    type: 'FixedValue',
    resourceType,
    path: absolutePath,
    severity,
    errorCode,
    params: {
      value: expectedValue,
    },
    userHint,
    message: '', // Will be generated by backend
    isMessageCustomized: false,
  };
}

/**
 * Parse a FixedValue rule for editing.
 * Extracts field path and expected value from rule definition.
 */
export function parseFixedValueRule(rule: Rule): {
  fieldPath: string;
  expectedValue: string;
} {
  // Extract field path from full path
  const pathParts = rule.path?.split('.') || [];
  const fieldPath = pathParts.slice(1).join('.');
  
  const expectedValue = rule.params?.value?.toString() || '';

  return {
    fieldPath,
    expectedValue,
  };
}
