import type { Rule } from '../../../../../types/rightPanelProps';
import type { InstanceScope } from '../../common/InstanceScope.types';
import { validateFieldPath } from '../../../../../utils/fieldPathValidator';

/**
 * FIXED VALUE RULE HELPERS
 * 
 * Build and parse FixedValue rules for the unified RuleForm architecture.
 * 
 * PHASE 4: Stores instanceScope and fieldPath as structured properties
 * FIXED ERROR CODE: FIXED_VALUE_MISMATCH (cannot be changed by user)
 * 
 * Rule Structure:
 * - type: "FixedValue"
 * - instanceScope: Structured instance scope object
 * - fieldPath: Resource-relative field path
 * - path: Legacy composed path (backward compat)
 * - params.value: Expected value
 * - errorCode: "FIXED_VALUE_MISMATCH" (fixed)
 */

interface BuildFixedValueRuleParams {
  resourceType: string;
  instanceScope: InstanceScope;
  fieldPath: string;
  expectedValue: string;
  severity: 'error' | 'warning' | 'information';
  userHint?: string;
}

/**
 * Build a FixedValue rule from form data.
 * PHASE 4: Stores instanceScope and fieldPath as separate properties
 */
export function buildFixedValueRule(params: BuildFixedValueRuleParams): Rule {
  const {
    resourceType,
    instanceScope,
    fieldPath,
    expectedValue,
    severity,
    userHint,
  } = params;

  // Validate field path (should be resource-relative)
  const validation = validateFieldPath(fieldPath);
  if (!validation.isValid) {
    throw new Error(`Invalid field path: ${validation.errorMessage}`);
  }

  return {
    id: `rule-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
    type: 'FixedValue',
    resourceType,
    instanceScope,
    fieldPath,
    severity,
    // errorCode removed - backend-owned
    params: {
      value: expectedValue,
    },
    userHint,
    message: '', // Will be generated by backend
    isMessageCustomized: false,
  };
}

/**
 * Parse a FixedValue rule for editing.
 * Extracts field path and expected value from rule definition.
 */
export function parseFixedValueRule(rule: Rule): {
  fieldPath: string;
  expectedValue: string;
} {
  // fieldPath is already resource-relative
  const fieldPath = rule.fieldPath || '';
  
  const expectedValue = rule.params?.value?.toString() || '';

  return {
    fieldPath,
    expectedValue,
  };
}
