import type { Rule } from '../../../../../types/rightPanelProps';
import type { InstanceScope } from '../../common/InstanceScope.types';
import { composeInstanceScopedPath } from '../../common/InstanceScope.utils';
import { validateFieldPath } from '../../../../../utils/fieldPathValidator';

/**
 * FIXED VALUE RULE HELPERS
 * 
 * Build and parse FixedValue rules for the unified RuleForm architecture.
 * 
 * PHASE 4: Stores instanceScope and fieldPath as structured properties
 * FIXED ERROR CODE: FIXED_VALUE_MISMATCH (cannot be changed by user)
 * 
 * Rule Structure:
 * - type: "FixedValue"
 * - instanceScope: Structured instance scope object
 * - fieldPath: Resource-relative field path
 * - path: Legacy composed path (backward compat)
 * - params.value: Expected value
 * - errorCode: "FIXED_VALUE_MISMATCH" (fixed)
 */

interface BuildFixedValueRuleParams {
  resourceType: string;
  instanceScope: InstanceScope;
  fieldPath: string;
  expectedValue: string;
  severity: 'error' | 'warning' | 'information';
  errorCode: string;
  userHint?: string;
}

/**
 * Compose full FHIRPath from components.
 * Used for backward compatibility with legacy path field.
 */
function composeFhirPath(
  resourceType: string,
  instanceScope: InstanceScope,
  fieldPath: string
): string {
  const scopePath = composeInstanceScopedPath(resourceType, instanceScope);
  return `${scopePath}.${fieldPath}`;
}

/**
 * Build a FixedValue rule from form data.
 * PHASE 4: Stores instanceScope and fieldPath as separate properties
 */
export function buildFixedValueRule(params: BuildFixedValueRuleParams): Rule {
  const {
    resourceType,
    instanceScope,
    fieldPath,
    expectedValue,
    severity,
    errorCode,
    userHint,
  } = params;

  // Validate field path (should be resource-relative)
  const validation = validateFieldPath(fieldPath);
  if (!validation.isValid) {
    throw new Error(`Invalid field path: ${validation.errorMessage}`);
  }

  // ✅ NEW: Store structured fields
  // ⚠️ Also compose legacy path for backward compatibility
  const legacyPath = composeFhirPath(resourceType, instanceScope, fieldPath);

  return {
    id: `rule-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
    type: 'FixedValue',
    resourceType,
    
    // ✅ NEW STRUCTURED FIELDS (PHASE 4)
    instanceScope,
    fieldPath,
    
    // ⚠️ DEPRECATED: Legacy path for backward compatibility
    path: legacyPath,
    
    severity,
    errorCode,
    params: {
      value: expectedValue,
    },
    userHint,
    message: '', // Will be generated by backend
    isMessageCustomized: false,
  };
}

/**
 * Parse a FixedValue rule for editing.
 * Extracts field path and expected value from rule definition.
 */
export function parseFixedValueRule(rule: Rule): {
  fieldPath: string;
  expectedValue: string;
} {
  // Extract field path from full path
  const pathParts = rule.path?.split('.') || [];
  const fieldPath = pathParts.slice(1).join('.');
  
  const expectedValue = rule.params?.value?.toString() || '';

  return {
    fieldPath,
    expectedValue,
  };
}
